<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

namespace GPBMetadata;

class Example
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
È
example.prototwitch.twirp.example"0
Hat
size (
color (	
name (	"
Size
inches (2O
Haberdasher@
MakeHat.twitch.twirp.example.Size.twitch.twirp.example.Hatbproto3'
        , true);

        static::$is_initialized = true;
    }
}

